version: "3.8"
services:
  springboot:
    container_name: springboot_postgres
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgresql:5432/db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    restart: always
    depends_on:
      - postgresql
    networks:
      - comment
  postgresql:
    image: postgres:10.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - comment

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - comment

networks:
  comment:
    driver: bridge